# Generated by Django 2.2.2 on 2019-06-27 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionscreen', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submissions',
            old_name='success',
            new_name='passed',
        ),
        migrations.AddField(
            model_name='submissions',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='submissions',
            name='programminglanguage',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='submissions',
            name='score',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='submissions',
            name='submitted_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
