# Generated by Django 2.2.2 on 2019-06-27 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionscreen', '0002_auto_20190627_0407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submissions',
            name='score',
            field=models.IntegerField(blank=True),
        ),
    ]
