# Generated by Django 2.2.2 on 2019-06-30 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionscreen', '0003_auto_20190627_0407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submissions',
            name='passed',
            field=models.BooleanField(blank=True),
        ),
    ]
