# Generated by Django 2.1.5 on 2019-07-26 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submissionid', models.IntegerField()),
                ('is_contest', models.BooleanField(default=False)),
                ('token', models.CharField(max_length=50)),
                ('base64_encoded', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('PENDING', 'Task Pending'), ('CORRECT', 'Right Answer'), ('WRONG', 'Wrong Answer'), ('RUNTIMEERROR', 'RUNTIME error')], max_length=20)),
                ('last_checked', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
