# Generated by Django 2.2.2 on 2019-06-18 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roundsubmissions',
            name='score',
            field=models.IntegerField(blank=True),
        ),
    ]
