# Generated by Django 2.2.2 on 2019-06-18 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0002_auto_20190618_1026'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roundsubmissions',
            name='question',
        ),
        migrations.RemoveField(
            model_name='roundsubmissions',
            name='thisround',
        ),
        migrations.AddField(
            model_name='roundsubmissions',
            name='roundquestion',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='timeline.RoundQuestions'),
            preserve_default=False,
        ),
    ]
