# Generated by Django 2.2.2 on 2019-06-18 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0003_auto_20190618_1056'),
    ]

    operations = [
        migrations.AddField(
            model_name='roundsubmissions',
            name='submitted_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
