# Generated by Django 2.2.2 on 2019-06-25 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0004_roundsubmissions_submitted_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roundquestions',
            name='question',
        ),
        migrations.RemoveField(
            model_name='roundquestions',
            name='thisround',
        ),
        migrations.RemoveField(
            model_name='rounds',
            name='competition',
        ),
        migrations.RemoveField(
            model_name='roundsubmissions',
            name='roundquestion',
        ),
        migrations.RemoveField(
            model_name='roundsubmissions',
            name='user',
        ),
        migrations.DeleteModel(
            name='Competitions',
        ),
        migrations.DeleteModel(
            name='RoundQuestions',
        ),
        migrations.DeleteModel(
            name='Rounds',
        ),
        migrations.DeleteModel(
            name='RoundSubmissions',
        ),
    ]
