# Generated by Django 2.2.2 on 2019-06-12 02:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(blank=True, max_length=30)),
                ('bio', models.TextField(blank=True, max_length=300)),
                ('website', models.CharField(blank=True, max_length=100)),
                ('school', models.CharField(blank=True, max_length=50)),
                ('college', models.CharField(blank=True, max_length=50)),
                ('work', models.CharField(blank=True, max_length=30)),
                ('receiveImpEmail', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
