# Generated by Django 2.2.2 on 2019-06-14 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_profile_facebookuserid'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='socialLinkFacebook',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='profile',
            name='socialLinkInsta',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='profile',
            name='socialLinkLinkedIn',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='profile',
            name='socialLinkTwitter',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
