# Generated by Django 2.2.2 on 2019-06-25 10:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('practice', '0003_questions_public'),
    ]

    operations = [
        migrations.CreateModel(
            name='Competitions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competitionName', models.CharField(max_length=20)),
                ('isActive', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='RoundQuestions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='practice.Questions')),
            ],
        ),
        migrations.CreateModel(
            name='RoundSubmissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now=True)),
                ('roundquestion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contest.RoundQuestions')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Rounds',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roundName', models.CharField(max_length=20)),
                ('participantsCount', models.IntegerField()),
                ('startdatetime', models.DateTimeField()),
                ('duration', models.DurationField()),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contest.Competitions')),
            ],
        ),
        migrations.AddField(
            model_name='roundquestions',
            name='thisround',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contest.Rounds'),
        ),
    ]
