# Generated by Django 2.1.5 on 2019-07-21 11:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Competitions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competitionName', models.CharField(max_length=20)),
                ('isActive', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='RoundQuestions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=200)),
                ('content', models.TextField(default='')),
                ('points', models.IntegerField(default=0)),
                ('subscore', models.IntegerField(default=0)),
                ('public', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Rounds',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roundName', models.CharField(max_length=20)),
                ('startdatetime', models.DateTimeField()),
                ('duration', models.DurationField()),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contest.Competitions')),
            ],
        ),
        migrations.CreateModel(
            name='RoundSubmissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now=True)),
                ('passed', models.BooleanField(blank=True)),
                ('checked', models.BooleanField(default=False)),
                ('gotSubscore', models.BooleanField(default=False)),
                ('content', models.TextField(blank=True)),
                ('programminglanguage', models.CharField(max_length=50)),
                ('roundquestion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contest.RoundQuestions')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RoundUsers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thisround', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contest.Rounds')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='roundquestions',
            name='thisround',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contest.Rounds'),
        ),
    ]
