# Generated by Django 2.2.2 on 2019-06-25 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roundquestions',
            name='question',
        ),
        migrations.AddField(
            model_name='roundquestions',
            name='content',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='roundquestions',
            name='points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='roundquestions',
            name='public',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='roundquestions',
            name='subscore',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='roundquestions',
            name='title',
            field=models.CharField(default='', max_length=200),
        ),
    ]
