# Generated by Django 2.1.5 on 2019-07-27 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0002_auto_20190725_0933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roundsubmissions',
            name='score',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
