# Generated by Django 2.2.2 on 2019-06-26 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0002_auto_20190625_1247'),
    ]

    operations = [
        migrations.AddField(
            model_name='roundsubmissions',
            name='passed',
            field=models.BooleanField(default=False),
        ),
    ]
