# Generated by Django 2.2.2 on 2019-06-26 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0003_roundsubmissions_passed'),
    ]

    operations = [
        migrations.AddField(
            model_name='roundsubmissions',
            name='content',
            field=models.TextField(blank=True),
        ),
    ]
