# Generated by Django 2.2.2 on 2019-06-26 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0004_roundsubmissions_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='roundsubmissions',
            name='programminglanguage',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
