# Generated by Django 2.2.2 on 2019-06-26 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0005_roundsubmissions_programminglanguage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roundsubmissions',
            name='programminglanguage',
            field=models.CharField(max_length=50),
        ),
    ]
