# Generated by Django 2.2.2 on 2019-06-27 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0006_auto_20190626_0931'),
    ]

    operations = [
        migrations.AddField(
            model_name='roundsubmissions',
            name='gotSubscore',
            field=models.BooleanField(default=False),
        ),
    ]
