# Generated by Django 2.2.2 on 2019-06-30 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0007_roundsubmissions_gotsubscore'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roundsubmissions',
            name='passed',
            field=models.BooleanField(blank=True),
        ),
    ]
