# Generated by Django 2.1 on 2019-07-20 15:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contest', '0009_roundsubmissions_checked'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoundUsers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thisround', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contest.Rounds')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
