# Generated by Django 2.1 on 2019-07-21 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0010_roundusers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rounds',
            name='participantsCount',
        ),
    ]
