# Generated by Django 2.2.2 on 2019-06-14 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='category',
            field=models.CharField(choices=[('MATH', 'Mathematics'), ('ALGO', 'Algorithms'), ('1A', 'Round 1A')], default='', max_length=20),
            preserve_default=False,
        ),
    ]
