# Generated by Django 2.2.2 on 2019-06-17 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0002_questions_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='public',
            field=models.BooleanField(default=False),
        ),
    ]
