# Generated by Django 2.1.5 on 2019-07-25 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0003_questions_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='expected_output',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='questions',
            name='stdin',
            field=models.TextField(default=''),
        ),
    ]
