# Generated by Django 2.2.2 on 2019-06-29 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misc', '0002_auto_20190629_0931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptions',
            name='email',
            field=models.CharField(max_length=40),
        ),
    ]
