# Generated by Django 2.2.2 on 2019-06-30 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misc', '0003_auto_20190629_0932'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriptions',
            name='id',
        ),
        migrations.AlterField(
            model_name='subscriptions',
            name='email',
            field=models.CharField(max_length=40, primary_key=True, serialize=False),
        ),
    ]
